---
- hosts: all
  become: true

  tasks:

    - name: Upgrade all packages
      apt: update_cache=yes upgrade=dist cache_valid_time=3600

    - name: Build sixpair
      script: build-sixpair.sh creates=/usr/local/bin/sixpair

    - name: Add Sixaxis USB udev rules
      copy: src=../etc/10-sixaxis-usb.rules dest=/etc/udev/rules.d/10-sixaxis-usb.rules owner=root group=root mode=0644
      notify:
        - reload udev rules

    # http://qtsixa.sourceforge.net
    - name: Build Sixad
      script: build-qtsixa.sh creates=/usr/sbin/sixad-bin

    - name: Copy sixad startup script
      copy: src=../etc/sixad dest=/usr/bin/sixad owner=root group=root mode=755

    - name: Add sixad service
      copy: src=../etc/sixad.service dest=/etc/systemd/system/sixad.service owner=root group=root mode=644
      notify:
        - reload services
        - enable sixad service
        - restart sixad service

    - name: Add bot service
      copy: src=../etc/bot.service dest=/etc/systemd/system/bot.service owner=root group=root mode=644
      notify:
        - reload services
        - enable bot service
        - restart bot service

  handlers:

    - name: reload udev rules
      command: udevadm control --reload-rules

    - name: reload services
      command: systemctl daemon-reload

    - name: enable sixad service
      service: name=sixad enabled=yes

    - name: restart sixad service
      service: name=sixad state=restarted

    - name: enable bot service
      service: name=bot enabled=yes

    - name: restart bot service
      service: name=bot state=restarted
