---
- hosts: all

  vars_files:
      - ../vars.yml

  tasks:
    - name: Disable systemd-journald persistence
      file: path=/var/log/journal/ state=absent
      notify:
        - restart journald

    - name: Disable Firstboot
      service: name=firstboot-graphical state=stopped enabled=no

    - name: Disable Headless mode
      service: name=headless-mode state=stopped enabled=no

    - name: Boot into multi-user (non-graphical) mode by default
      file: src=/usr/lib/systemd/system/multi-user.target dest=/etc/systemd/system/default.target owner=root group=root mode=777 state=link
      notify:
        - enter default mode

    # Configure wireless
    # See: http://fedoraproject.org/wiki/Tools/NetworkManager/CLI
    - name: Configure wireless
      command: "nmcli device wifi connect {{wifi_ssid}} password {{wifi_psk}} creates=/etc/sysconfig/network-scripts/ifcfg-{{wifi_ssid}}"

    - name: Build sixpair
      script: build-sixpair.sh creates=/usr/local/bin/sixpair

    - name: Add Sixaxis USB udev rules
      copy: src=../etc/10-sixaxis-usb.rules dest=/etc/udev/rules.d/10-sixaxis-usb.rules owner=root group=root mode=0644
      notify:
        - reload udev rules

    # http://qtsixa.sourceforge.net
    - name: Build Sixad
      script: build-qtsixa.sh creates=/usr/sbin/sixad-bin

    - name: Copy sixad startup script
      copy: src=sixad dest=/usr/bin/sixad owner=root group=root mode=755

    - name: Add sixad service
      copy: src=../etc/sixad.service dest=/etc/systemd/system/sixad.service owner=root group=root mode=644
      notify:
        - reload services
        - enable sixad service
        - restart sixad service

    - name: Add bot service
      copy: src=../etc/bot.service dest=/etc/systemd/system/bot.service owner=root group=root mode=644
      notify:
        - reload services
        - enable bot service
        - restart bot service

  handlers:
    - name: enter default mode
      command: systemctl default

    - name: restart journald
      service: name=systemd-journald state=restarted

    - name: reload udev rules
      command: udevadm control --reload-rules

    - name: reload services
      command: systemctl daemon-reload

    - name: enable bot service
      service: name=bot enabled=yes

    - name: restart bot service
      service: name=bot state=restarted

    - name: enable sixad service
      service: name=sixad enabled=yes

    - name: restart sixad service
      service: name=sixad state=restarted
